### ISSUE TITLE
Create GitHub Action for linting Back End code

### ISSUE THREAD

**Issue by terrameijar** [PythonBulawayo/ChitChat#27]

**Comment by ChikangaTakudzwa** [comment]
is it possible to assign the people working on issues on the issues

**Comment by ChikangaTakudzwa** [comment]
i will make an action and create a pull request, but does it have to pass in my fork or when merged people will have to fix their code to make the lint pass

**Comment by terrameijar** [comment]
This was resolved in https://github.com/PythonBulawayo/ChitChat/pull/45
