### ISSUE TITLE
Add software license

### ISSUE THREAD

**Issue by terrameijar** [PythonBulawayo/ChitChat#3]
This project does not have a license yet. I'm creating this ticket so we remember to do it and to allow us to have a discussion about it before we settle on one.

[This ](https://choosealicense.com/)is a good resource to learn about the different types of open-source software licenses.

Another good resource that also covers how to add licenses to projects is [this one](https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/)

**Comment by im-machakata** [comment]
Hi, I would love to work on this.

**Comment by terrameijar** [comment]
@im-machakata go for it!

**Comment by im-machakata** [comment]
You forgot to close this @terrameijar 😉

**Comment by terrameijar** [comment]
Thanks for the reminder @im-machakata
