### ISSUE TITLE
Add flake8 to `requirements.txt` in the backend.

### ISSUE THREAD

**Issue by terrameijar** [PythonBulawayo/ChitChat#32]
Steps to follow:

- create a feature branch
- Follow backend setup instructions in the README
- Add the latest version of flake8 to the `requirements.txt` file. At the time of writing the latest flake8 version is 7.0.0 so the requirements entry should be:

`flake8==7.0.0`

- commit changes, push them up to your fork
- create a Pull Request against the `develop` branch

**Comment by terrameijar** [comment]
@chikangatakudzwa is working on this issue

**Comment by ChikangaTakudzwa** [comment]
on it

**Comment by ChikangaTakudzwa** [comment]
Created a pull request

**Comment by terrameijar** [comment]
@ChikangaTakudzwa Thank you, I see it.
