### ISSUE TITLE
Create base HTML and CSS design

### ISSUE THREAD

**Issue by terrameijar** [PythonBulawayo/ChitChat#64]
Create a base HTML and CSS template from which all pages will inherit. Requirements:

- Site Logo
- Responsive
- Top navbar
- 2 sidebars and a main content area. Side bars on either side of the main content area, like the design below:

![image](https://github.com/user-attachments/assets/3fcebbb9-3ab3-44fa-89dc-14f75b420d8b)

**Comment by TanyaMushonga** [comment]
Working on this now

**Comment by terrameijar** [comment]
Fixed in https://github.com/PythonBulawayo/ChitChat/pull/65. Thank you @TanyaMushonga
